modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/rinchanai/waystone-emeralds/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/rinchanai/waystone-emeralds"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="waystones"
type="required"
versionRange="[21.1.32,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="balm"
type="required"
versionRange="[21.0.39,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="lightmanscurrency"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
